### ISSUE TITLE
issue while serialize a  array 

### ISSUE THREAD

**Issue by vinothkrstatiq** [nopnop2002/esp-idf-json#4]
[
  2,
  "531531531",
  "BootNotification",
  {
    "chargePointModel": "vinoth",
    "chargePointVendor": "kannan"
  }
]

above is  Json array could you help me to serialize the above array?
I tried but not able to succeed 
but i am able to  deserialize
const char *nn = "[2,\"531531531\",\"BootNotification\",{\"chargePointModel\":\"vinoth\",\"chargePointVendor\":\"kannan\"}]";
	cJSON *root = cJSON_Parse(nn);

	cJSON *e1 = cJSON_GetArrayItem(root, 0);
	printf(" id %d \n", e1->valueint);
	cJSON *e2 = cJSON_GetArrayItem(root, 1);
	printf(" id %s \n", e2->valuestring);
	cJSON *e3 = cJSON_GetArrayItem(root, 2);
	printf(" id %s \n", e3->valuestring);
	cJSON *e4 = cJSON_GetArrayItem(root, 3);
	cJSON *e41 = cJSON_GetObjectItem(e4, "chargePointModel");
	printf(" id %s \n", e41->valuestring);
	cJSON *e42 = cJSON_GetObjectItem(e4, "chargePointVendor");
	printf(" id %s \n", e42->valuestring);

	cJSON_Delete(root);

it is working 
i need your help to serialize

**Comment by nopnop2002** [comment]
I added json-basic-array/json-complex-array example.

I think json-complex-array will help you.

---

Renamed from json-complex-array to json-object-in-array

**Comment by vinothkrstatiq** [comment]
@nopnop2002 thanks a lot it helped me 
Similarly, Do you have example for how to serialize below array?
[
  2,
  "531531538",
  "MeterValues",
  {
    "connectorId": 1,
    "meterValue": [
      {
        "timestamp": "2022-05-21T17:03:53.000Z",
        "sampledValue": [
          {
            "context": "Sample.Periodic",
            "location": "Outlet",
            "measurand": "Energy.Active.Import.Register",
            "unit": "Wh",
            "value": "140.09"
          },
          {
            "context": "Sample.Periodic",
            "location": "Outlet",
            "measurand": "Voltage",
            "unit": "V",
            "value": "230.00"
          },
          {
            "context": "Sample.Periodic",
            "location": "Outlet",
            "measurand": "Current.Import",
            "unit": "A",
            "value": "16.62"
          }
        ]
      }
    ],
    "transactionId": 10000938
  }
]

**Comment by nopnop2002** [comment]
```
[ <--- start array. This is root.
2,
"531531538",
"MeterValues",
{ <--- start object. This is object in array.
"connectorId": 1,
"meterValue": [ <--- start array. This is array in object.
{ <--- start object. This is object in array.
"timestamp": "2022-05-21T17:03:53.000Z",
"sampledValue": [ <--- start array. This is array in object
{ <--- start object. This is object in array.
"context": "Sample.Periodic",
"location": "Outlet",
"measurand": "Energy.Active.Import.Register",
"unit": "Wh",
"value": "140.09"
}, <--- end object
{ <--- start object. This is object in array.
"context": "Sample.Periodic",
"location": "Outlet",
"measurand": "Voltage",
"unit": "V",
"value": "230.00"
}, <--- end object
{ <--- start object. This is object in array.
"context": "Sample.Periodic",
"location": "Outlet",
"measurand": "Current.Import",
"unit": "A",
"value": "16.62"
} <--- end object
] <--- end array
} <--- end object
], <--- end array
"transactionId": 10000938
} <--- end object
] <--- end array
```

This is complex of [object in array] and [array in object].


json-array-in-object and json-object-in-array are helpful.

**Comment by vinothkrstatiq** [comment]
@nopnop2002 
After a long attempt finally, I serialized the above JSON Thank you so much
appreciated your cJSON work. your examples help me a lot.
