### ISSUE TITLE
 JSON PARSING crashed

### ISSUE THREAD

**Issue by sandipmaurya** [nopnop2002/esp-idf-json#6]
If particular object is not there in JSON then while JSON parsing program going to crashed

**Comment by nopnop2002** [comment]
You can use cJSON_GetObjectItem().

https://github.com/nopnop2002/esp-idf-json/blob/master/json-basic-object/main/main.c#L31

---

This repository shows how to use the cJSON library.
Please post any issues against the cJSON library here.
https://github.com/espressif/esp-idf/issues
